[build]
  command = "ng build && ng run angular-serverless:serverless:production"
  functions = "netlify/functions"
  publish = "dist/angular-serverless/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
